# Copyright (c) 2025 Your Name — github.com/h4ckcrypt/PhantomX
# Non-commercial use only. See LICENSE.

"""
PROJECT STRUCTURE 
─────────────────────────────────────
project/
├── server/app.py
├── tracker/
│   ├── logger.py
│   └── campaign_store.py
├── ai/
│   ├── predictor.py
│   └── model.pkl           (generated by train_model.py)
├── analyzer/
│   ├── scorer.py
│   ├── feature_extractor.py
│   ├── feature_utils.py
│   ├── intent.py
│   └── anomaly.py
├── templates/
│   ├── admin/              ← dashboard UI (NOT phishing pages)
│   │   ├── dashboard.html
│   │   ├── session.html
│   │   ├── campaigns.html
│   │   └── campaign_detail.html
│   ├── login_basic/        ← phishing template 1
│   │   ├── index.html      (uses %%SESSION_ID%%, /t/login_basic/assets/...)
│   │   └── assets/
│   │       ├── js/
│   │       │   ├── tracker.js      (copy here for each template)
│   │       │   ├── template.js     (template-specific UI logic)
│   │       │   ├── jquery-3.4.1.min.js
│   │       │   └── ...
│   │       ├── css/
│   │       └── images/
│   ├── login_microsoft/    ← phishing template 2 (future)
│   │   ├── index.html
│   │   └── assets/...
│   └── login_dropbox/      ← phishing template 3 (future)
│       └── ...
├── logs/
│   ├── sessions.json
│   ├── training_data.json
│   ├── campaigns.json
│   └── baseline.json
├── simulator.py
└── README.md
"""

import datetime
import json
import os
import secrets
import time
import uuid
from functools import wraps

from flask import (Flask, jsonify, redirect, render_template,
                   render_template_string, request, send_from_directory,
                   session, url_for)
from werkzeug.middleware.proxy_fix import ProxyFix

from ai.predictor import predict_user
from analyzer.scorer import calculate_score, classify_user
from tracker.logger import log_event
from tracker.campaign_store import (
    create_campaign, get_campaign, list_campaigns,
    update_campaign_status, delete_campaign,
    add_target, add_targets_bulk,
    get_target_by_token, get_target,
    record_flow_step, mark_email_sent,
    compute_metrics, FLOW_STEPS, OUTCOME_RANK,
)

BASE_DIR       = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATES_DIR  = os.path.join(BASE_DIR, "templates")         
ADMIN_DIR      = os.path.join(TEMPLATES_DIR, "admin")        
LOG_FILE       = os.path.join(BASE_DIR, "logs", "sessions.json")
PUBLIC_URL     = os.environ.get("PUBLIC_URL", "http://127.0.0.1:5000")


DEFAULT_TEMPLATE = os.environ.get("SELECTED_TEMPLATE", "login_basic")

ADMIN_USER = os.environ.get("ADMIN_USER", "admin")
ADMIN_PASS = os.environ.get("ADMIN_PASS", "admin1234")

app = Flask(
    __name__,
   
    template_folder=ADMIN_DIR,
)

_KEY_FILE = os.path.join(BASE_DIR, "logs", ".secret_key")


def _load_or_create_secret_key() -> str:
    env_key = os.environ.get("SECRET_KEY")
    if env_key:
        return env_key
    os.makedirs(os.path.dirname(_KEY_FILE), exist_ok=True)
    if os.path.exists(_KEY_FILE):
        key = open(_KEY_FILE).read().strip()
        if len(key) >= 32:
            return key
    key = secrets.token_hex(32)
    open(_KEY_FILE, "w").write(key)
    return key


app.secret_key = _load_or_create_secret_key()
app.config["SESSION_PERMANENT"] = False
app.config["PERMANENT_SESSION_LIFETIME"] = datetime.timedelta(days=30)
app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1, x_host=1)

def list_phishing_templates() -> list[str]:

    result = []
    if not os.path.isdir(TEMPLATES_DIR):
        return result
    for name in sorted(os.listdir(TEMPLATES_DIR)):
        if name == "admin":
            continue
        t_path = os.path.join(TEMPLATES_DIR, name)
        if os.path.isdir(t_path) and os.path.exists(os.path.join(t_path, "index.html")):
            result.append(name)
    return result


def resolve_template(name: str) -> str:
    
    safe_name = os.path.basename(name) if name else DEFAULT_TEMPLATE
    t_path    = os.path.join(TEMPLATES_DIR, safe_name)
    if os.path.isdir(t_path) and os.path.exists(os.path.join(t_path, "index.html")):
        return safe_name
    return DEFAULT_TEMPLATE


def serve_template_page(template_name: str,
                        session_id: str,
                        cid: str = "",
                        uid: str = "") -> str:
    """
    Load index.html from the given template, replace %%MARKERS%%,
    and return the rendered HTML string.

    MARKERS (double-percent — no Jinja2 collision):
        %%SESSION_ID%%    → session UUID
        %%CAMPAIGN_ID%%   → campaign id or ""
        %%USER_ID%%       → user id or ""
        %%TEMPLATE_NAME%% → template folder name (for asset URLs)

    Each template's index.html uses:
        /t/%%TEMPLATE_NAME%%/assets/js/tracker.js
    which resolves to e.g.:
        /t/login_basic/assets/js/tracker.js
    """
    t_path    = os.path.join(TEMPLATES_DIR, template_name)
    index_path = os.path.join(t_path, "index.html")

    with open(index_path, "r", encoding="utf-8") as f:
        html = f.read()

    html = html.replace("%%SESSION_ID%%",    session_id)
    html = html.replace("%%CAMPAIGN_ID%%",   cid)
    html = html.replace("%%USER_ID%%",       uid)
    html = html.replace("%%TEMPLATE_NAME%%", template_name)

    html = html.replace("{{SESSION_ID}}",    session_id)
    html = html.replace("{{CAMPAIGN_ID}}",   cid)
    html = html.replace("{{USER_ID}}",       uid)
    html = html.replace("{{TEMPLATE_NAME}}", template_name)

    
    return html

def _read_log() -> dict:
    try:
        with open(LOG_FILE) as f:
            data = json.load(f)
        return data if isinstance(data, dict) else {}
    except (FileNotFoundError, json.JSONDecodeError):
        return {}


def _write_log(data: dict) -> None:
    os.makedirs(os.path.dirname(LOG_FILE), exist_ok=True)
    tmp = LOG_FILE + ".tmp"
    with open(tmp, "w") as f:
        json.dump(data, f, indent=2)
    os.replace(tmp, LOG_FILE)


def _unwrap_session(session_data):
    if isinstance(session_data, dict):
        return session_data.get("events", []), session_data.get("status", "active")
    if isinstance(session_data, list):
        return session_data, "unknown"
    return [], "unknown"


def _live_status(events: list, stored: str) -> str:
    if not events:
        return stored
    last_ev = events[-1].get("event", "")
    last_ts = events[-1].get("timestamp", 0)
    if last_ev == "page_close" or stored == "closed":
        return "closed"
    if time.time() - last_ts > 30:
        return "idle"
    return "active"


def _ai_blend(heuristic: float, ai_label: str) -> float:
    modifier = {"High Risk": 10, "Suspicious": 5, "Safe": -3}.get(ai_label, 0)
    return max(0.0, min(100.0, heuristic + modifier))


def _build_session_row(sid: str, sdata) -> dict | None:
    events, stored = _unwrap_session(sdata)
    if not events:
        return None
    h        = calculate_score(events)
    ai_label = predict_user(events)
    score    = _ai_blend(h, ai_label)
    return {
        "id":            sid,
        "id_short":      sid[:8],
        "score":         round(score, 1),
        "category":      classify_user(score),
        "status":        _live_status(events, stored),
        "events":        len(events),
        "ai_prediction": ai_label,
        "campaign_id":   sdata.get("campaign_id") if isinstance(sdata, dict) else None,
        "user_id":       sdata.get("user_id")     if isinstance(sdata, dict) else None,
    }


def _tracking_url(token: str) -> str:
    return PUBLIC_URL.rstrip("/") + "/go?tok=" + token


def require_admin(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if not session.get("admin_logged_in"):
            return redirect(url_for("login", next=request.path))
        return f(*args, **kwargs)
    return decorated


@app.route("/login", methods=["GET", "POST"])
def login():
    error = None
    if request.method == "POST":
        u = request.form.get("username", "").strip()
        p = request.form.get("password", "").strip()
        if u == ADMIN_USER and p == ADMIN_PASS:
            session["admin_logged_in"] = True
            return redirect(request.args.get("next") or url_for("dashboard"))
        error = "Invalid credentials."

    LOGIN_HTML = """<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>Admin Login</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{background:#0f172a;display:flex;align-items:center;justify-content:center;
     min-height:100vh;font-family:Arial,sans-serif}
.card{background:#1e293b;border-radius:14px;padding:40px 36px;width:340px}
h1{color:#f1f5f9;font-size:1.3rem;margin-bottom:6px}
p.sub{color:#64748b;font-size:.82rem;margin-bottom:28px}
label{display:block;font-size:.8rem;color:#94a3b8;text-transform:uppercase;
      letter-spacing:.05em;margin-bottom:6px}
input{width:100%;padding:10px 14px;border-radius:8px;border:1px solid #334155;
      background:#0f172a;color:#e2e8f0;font-size:.95rem;margin-bottom:18px;outline:none}
input:focus{border-color:#38bdf8}
button{width:100%;padding:11px;border-radius:8px;border:none;background:#0ea5e9;
       color:#fff;font-size:1rem;font-weight:600;cursor:pointer}
button:hover{background:#0284c7}
.err{color:#ef4444;font-size:.83rem;margin-bottom:14px;padding:8px 12px;
     background:#450a0a;border-radius:6px}
.lock{font-size:2.4rem;margin-bottom:18px;text-align:center}
</style></head><body>
<div class="card">
  <div class="lock">🔒</div>
  <h1>Admin Login</h1><p class="sub">Security Intelligence Dashboard</p>
  {% if error %}<div class="err">{{ error }}</div>{% endif %}
  <form method="POST">
    <label>Username</label>
    <input name="username" type="text" autocomplete="username" required>
    <label>Password</label>
    <input name="password" type="password" autocomplete="current-password" required>
    <button type="submit">Sign In →</button>
  </form>
</div></body></html>"""
    return render_template_string(LOGIN_HTML, error=error)


@app.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("login"))



@app.route("/t/<template_name>/assets/<path:filename>")
def serve_template_assets(template_name, filename):

    safe_name  = resolve_template(template_name)
    assets_dir = os.path.join(TEMPLATES_DIR, safe_name, "assets")
    return send_from_directory(assets_dir, filename)


@app.route("/assets/<path:filename>")
def serve_assets_legacy(filename):
    
    assets_dir = os.path.join(TEMPLATES_DIR, DEFAULT_TEMPLATE, "assets")
    return send_from_directory(assets_dir, filename)



@app.route("/go")
def tracking_entry():
    token = request.args.get("tok", "")
    cid, uid, target = get_target_by_token(token)

    if not cid:
        
        return redirect("/")

    record_flow_step(cid, uid, "link_clicked")
    record_flow_step(cid, uid, "page_visited")

    campaign = get_campaign(cid) or {}
    template = resolve_template(campaign.get("template", DEFAULT_TEMPLATE))

    return redirect(f"/?cid={cid}&uid={uid}&tpl={template}")



@app.route("/")
def index():
    cid      = request.args.get("cid", "")
    uid      = request.args.get("uid", "")
    
    template = resolve_template(request.args.get("tpl", DEFAULT_TEMPLATE))

    session_id = str(uuid.uuid4())

    if cid and uid:
        record_flow_step(cid, uid, "page_visited", session_id=session_id)

    log_event(session_id, "page_open", cid=cid or None, uid=uid or None)

    try:
        html = serve_template_page(template, session_id, cid, uid)
    except FileNotFoundError:
        
        html = serve_template_page(DEFAULT_TEMPLATE, session_id, cid, uid)

    
    from flask import Response
    return Response(html, mimetype="text/html")



@app.route("/track", methods=["POST"])
def track():
    data = request.get_json(silent=True)
    if not data:
        try:
            data = json.loads(request.data.decode("utf-8"))
        except Exception:
            data = {}

    session_id = data.get("session_id")
    event      = data.get("event")
    extra      = data.get("data", {})
    cid        = data.get("campaign_id") or None
    uid        = data.get("user_id")     or None

    log_event(session_id, event, extra, cid=cid, uid=uid)

    if cid and uid:
        if event in ("keypress", "input_change", "field_focus"):
            record_flow_step(cid, uid, "interaction", session_id=session_id)
        elif event == "form_submit":
            record_flow_step(cid, uid, "compromised", session_id=session_id)

    return jsonify({"status": "ok"})


@app.route("/close", methods=["POST"])
def close():
    return track()



@app.route("/dashboard")
@require_admin
def dashboard():
    data     = _read_log()
    sessions = []
    for sid, sdata in data.items():
        row = _build_session_row(sid, sdata)
        if row:
            sessions.append(row)
    sessions.sort(key=lambda s: s["score"], reverse=True)
    return render_template("dashboard.html", sessions=sessions)


@app.route("/campaigns")
@require_admin
def campaigns_page():
    return render_template("campaigns.html")


@app.route("/campaign/<cid>")
@require_admin
def campaign_detail_page(cid):
    return render_template("campaign_detail.html", campaign_id=cid)


@app.route("/session/<session_id>")
@require_admin
def session_detail(session_id):
    return render_template("session.html", session_id=session_id)




@app.route("/api/sessions")
@require_admin
def api_sessions():
    data   = _read_log()
    result = []
    for sid, sdata in data.items():
        row = _build_session_row(sid, sdata)
        if row:
            result.append(row)
    result.sort(key=lambda s: s["score"], reverse=True)
    return jsonify(result)


@app.route("/api/session/<session_id>")
@require_admin
def api_session_detail(session_id):
    data       = _read_log()
    sdata      = data.get(session_id, {})
    events, st = _unwrap_session(sdata)
    return jsonify({"events": events, "status": _live_status(events, st)})


@app.route("/api/session/<session_id>", methods=["DELETE"])
@require_admin
def api_delete_session(session_id):
    data = _read_log()
    if session_id not in data:
        return jsonify({"error": "Not found"}), 404
    del data[session_id]
    _write_log(data)
    return jsonify({"status": "deleted"})


@app.route("/api/sessions", methods=["DELETE"])
@require_admin
def api_clear_sessions():
    body = request.get_json(silent=True) or {}
    if not body.get("confirm"):
        return jsonify({"error": 'Send {"confirm": true}'}), 400
    _write_log({})
    return jsonify({"status": "cleared"})


@app.route("/api/session/<session_id>/analysis")
@require_admin
def api_session_analysis(session_id):
    data        = _read_log()
    sdata       = data.get(session_id)
    if sdata is None:
        return jsonify({"error": "Session not found"}), 404

    events, stored_status = _unwrap_session(sdata)
    if not events:
        return jsonify({"error": "No events"}), 404

    status = _live_status(events, stored_status)

    clicks          = sum(1 for e in events if e.get("event") == "click")
    keypresses      = sum(1 for e in events if e.get("event") == "keypress")
    inputs_ev       = sum(1 for e in events if e.get("event") in ("input", "input_change"))
    tab_switches    = sum(1 for e in events if e.get("event") == "tab_hidden")
    mousemoves      = sum(1 for e in events if e.get("event") == "mousemove")
    idle_events     = [e for e in events if e.get("event") == "idle"]
    form_submit     = any(e.get("event") == "form_submit" for e in events)
    form_attempt    = any(e.get("event") == "form_submit_attempt" for e in events)
    copy_events     = sum(1 for e in events if e.get("event") == "copy")
    paste_events    = sum(1 for e in events if e.get("event") == "paste")
    autofill_ev     = [e for e in events if e.get("event") == "autofill"]
    field_focus_ev  = [e for e in events if e.get("event") == "field_focus"]

    duration = 0
    if len(events) >= 2:
        duration = events[-1].get("timestamp", 0) - events[0].get("timestamp", 0)
    max_idle = max((e.get("data", {}).get("duration", 0) for e in idle_events), default=0)

    h        = calculate_score(events)
    ai_label = predict_user(events)
    score    = _ai_blend(h, ai_label)
    category = classify_user(score)

    has_click = clicks > 0
    has_type  = (keypresses + inputs_ev) > 0

    if not has_click and not has_type:
        eng_val, eng_why = "None",    "No clicks or keystrokes — possible bot or bounce"
    elif has_click and not has_type:
        eng_val, eng_why = "Low",     f"Clicked {clicks}× but never typed"
    elif has_click and has_type:
        eng_val, eng_why = "High",    f"Clicked {clicks}× and typed {keypresses+inputs_ev} keypress(es)"
    else:
        eng_val, eng_why = "Partial", "Typed without clicking"

    if mousemoves == 0:
        m_val, m_why = "None",   "No mouse movement"
    elif mousemoves < 10:
        m_val, m_why = "Low",    f"Only {mousemoves} movement(s)"
    elif mousemoves < 40:
        m_val, m_why = "Normal", "Continuous non-linear movement — human browsing"
    else:
        m_val, m_why = "High",   f"Extensive activity ({mousemoves} movements)"

    if keypresses == 0 and inputs_ev == 0:
        t_val, t_why = "None",    "No keypress or input events"
    elif keypresses < 5:
        t_val, t_why = "Minimal", f"Only {keypresses} keypress(es)"
    else:
        t_val, t_why = "Active",  f"{keypresses} keypress(es) — manually typed"

    n_focus = len(field_focus_ev)
    fm      = [e.get("data", {}).get("method", "?") for e in field_focus_ev]
    if n_focus == 0:
        fi_val, fi_why = "None", "No input field interactions"
    else:
        fi_val = "Active"
        fi_why = f"{n_focus} focus event(s): {fm.count('click')} click, {fm.count('tab')} tab"

    if tab_switches == 0:
        tab_val, tab_why = "None",     "Stayed on page"
    elif tab_switches <= 2:
        tab_val, tab_why = "Moderate", f"Switched tabs {tab_switches}×"
    else:
        tab_val, tab_why = "High",     f"Switched tabs {tab_switches}× — frequent"

    if not idle_events:
        idle_val, idle_why = "None",    "No idle periods"
    elif max_idle < 10:
        idle_val, idle_why = "Brief",   f"{round(max_idle,1)}s inactivity"
    elif max_idle < 30:
        idle_val, idle_why = "Present", f"{round(max_idle,1)}s pause"
    else:
        idle_val, idle_why = "Long",    f"{round(max_idle,1)}s extended idle"

    cp = copy_events + paste_events
    if cp == 0:
        cp_val, cp_why = "None", "No copy or paste activity"
    else:
        parts = []
        if copy_events:  parts.append(f"{copy_events} copy")
        if paste_events: parts.append(f"{paste_events} paste")
        cp_val = "Detected"
        cp_why = f"{' + '.join(parts)} event(s)"

    n_af = len(autofill_ev)
    if n_af == 0:
        af_val, af_why = "None",    "Fields typed manually"
    elif keypresses < 3:
        af_val, af_why = "Full",    f"{n_af} field(s) via autofill"
    else:
        af_val, af_why = "Partial", f"{n_af} autofill + manual typing"

    if form_submit:
        sub_val, sub_why = "Yes",       "Form submitted — credentials captured"
    elif form_attempt:
        sub_val, sub_why = "Attempted", "Tried to submit, invalid email"
    else:
        sub_val, sub_why = "No",        "Did not submit"

    return jsonify({
        "session_id":    session_id,
        "status":        status,
        "risk_score":    round(score, 1),
        "risk_category": category,
        "ai_prediction": ai_label,
        "duration_s":    round(duration, 1),
        "event_count":   len(events),
        "campaign_id":   sdata.get("campaign_id") if isinstance(sdata, dict) else None,
        "user_id":       sdata.get("user_id")     if isinstance(sdata, dict) else None,
        "behaviours": [
            {"label": "Engagement",       "value": eng_val,  "reason": eng_why,  "icon": "🎯"},
            {"label": "Mouse Activity",    "value": m_val,    "reason": m_why,    "icon": "🖱️"},
            {"label": "Typing",            "value": t_val,    "reason": t_why,    "icon": "⌨️"},
            {"label": "Field Interaction", "value": fi_val,   "reason": fi_why,   "icon": "🖊️"},
            {"label": "Autofill",          "value": af_val,   "reason": af_why,   "icon": "🤖"},
            {"label": "Tab Behaviour",     "value": tab_val,  "reason": tab_why,  "icon": "🗂️"},
            {"label": "Idle Periods",      "value": idle_val, "reason": idle_why, "icon": "⏱️"},
            {"label": "Copy-Paste",        "value": cp_val,   "reason": cp_why,   "icon": "📋"},
            {"label": "Form Submitted",    "value": sub_val,  "reason": sub_why,  "icon": "📨"},
        ],
    })



@app.route("/api/templates")
@require_admin
def api_list_templates():
    
    return jsonify(list_phishing_templates())


@app.route("/api/campaigns", methods=["GET"])
@require_admin
def api_list_campaigns():
    camps = list_campaigns()
    for c in camps:
        c["tracking_base"] = PUBLIC_URL.rstrip("/") + "/go?tok="
    return jsonify(camps)


@app.route("/api/campaigns", methods=["POST"])
@require_admin
def api_create_campaign():
    body = request.get_json(silent=True) or {}
    name = body.get("name", "").strip()
    if not name:
        return jsonify({"error": "name is required"}), 400
    template   = resolve_template(body.get("template", DEFAULT_TEMPLATE))
    start_time = body.get("start_time")
    end_time   = body.get("end_time")
    campaign   = create_campaign(name, template, start_time, end_time)
    return jsonify(campaign), 201


@app.route("/api/campaigns/<cid>", methods=["GET"])
@require_admin
def api_get_campaign(cid):
    c = get_campaign(cid)
    if not c:
        return jsonify({"error": "Not found"}), 404
    metrics = compute_metrics(cid)
    targets = []
    for uid, t in c.get("targets", {}).items():
        targets.append({**t, "tracking_url": _tracking_url(t["link_token"])})
    return jsonify({**c, "targets": targets, "metrics": metrics})


@app.route("/api/campaigns/<cid>/status", methods=["PATCH"])
@require_admin
def api_update_campaign_status(cid):
    body   = request.get_json(silent=True) or {}
    status = body.get("status", "")
    if status not in ("active", "paused", "completed"):
        return jsonify({"error": "status must be active|paused|completed"}), 400
    if not update_campaign_status(cid, status):
        return jsonify({"error": "Not found"}), 404
    return jsonify({"status": status})


@app.route("/api/campaigns/<cid>", methods=["DELETE"])
@require_admin
def api_delete_campaign(cid):
    if not delete_campaign(cid):
        return jsonify({"error": "Not found"}), 404
    return jsonify({"status": "deleted"})


@app.route("/api/campaigns/<cid>/targets", methods=["POST"])
@require_admin
def api_add_target(cid):
    body  = request.get_json(silent=True) or {}
    email = body.get("email", "").strip()
    if not email:
        return jsonify({"error": "email required"}), 400
    target = add_target(cid, email, body.get("name", "").strip())
    if not target:
        return jsonify({"error": "Campaign not found"}), 404
    return jsonify({**target, "tracking_url": _tracking_url(target["link_token"])}), 201


@app.route("/api/campaigns/<cid>/targets/bulk", methods=["POST"])
@require_admin
def api_add_targets_bulk(cid):
    content_type = request.content_type or ""
    if "application/json" in content_type:
        body    = request.get_json(silent=True) or {}
        entries = body.get("targets", [])
    else:
        lines   = request.data.decode("utf-8").strip().splitlines()
        entries = []
        for line in lines:
            parts = [p.strip() for p in line.split(",")]
            if parts and parts[0]:
                entries.append({"email": parts[0], "name": parts[1] if len(parts) > 1 else ""})

    created = add_targets_bulk(cid, entries)
    result  = [{**t, "tracking_url": _tracking_url(t["link_token"])} for t in created]
    return jsonify({"created": len(result), "targets": result}), 201


@app.route("/api/campaigns/<cid>/targets/<uid>/email_sent", methods=["POST"])
@require_admin
def api_mark_email_sent(cid, uid):
    if not mark_email_sent(cid, uid):
        return jsonify({"error": "Not found"}), 404
    return jsonify({"status": "recorded"})


@app.route("/api/campaigns/<cid>/metrics", methods=["GET"])
@require_admin
def api_campaign_metrics(cid):
    if not get_campaign(cid):
        return jsonify({"error": "Not found"}), 404
    return jsonify(compute_metrics(cid))


if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0", port=5000)
